### ISSUE TITLE
Consolidate platform function pointers into one structure member in sbi_platform structure

### ISSUE THREAD

**Issue by changab** [riscv/opensbi#108]
The current design of sbi_platform table seems not flexible to add new structure member. We should consolidate those platform function pointers into one structure member in sbi_platform. So any new Non-function pointer member added to sbi_platform doesn’t bother the order of platform function pointers listed in structure and keep the backward compatibility, also the structure looks nicer.

**Comment by avpatel** [comment]
Patches for this are merged now. Thanks Abner.

**Comment by changab** [comment]
Thanks, Anup,
Now it is UEFI/PI effort to play with opensbi.
