### ISSUE TITLE
Add two new members to sbi_platform structure. One to indicate the openSBI version this table is created base on. Another is a pointer to firmware-system information.

### ISSUE THREAD

**Issue by changab** [riscv/opensbi#109]
This issue has dependence with #108. Better to reorganize sbi_platform structure first and then add these two new members.
**opensbi_revision**
On UEFI EDK2, 23 will have entire OpenSBI code tree under EDK2 RiscVPkg, however, we won’t use platform code under OpenSBI. Instead, we will leverage some of OpenSBI platform code and create RISC-V platform tree under EDK2 Platform repo which follows EDK2 implementation. 
EDK2 RISC-V platform code is expected to deliver by the vendor and separated from OpenSBI release, this means RISC-V platform code is possible not align with OpenSBI on EDK2 code tree because edk2 RISC-V package is maintained by EDK2 owner other than vendors. Furthermore, OEM may maintain their own in-house UEFI BIOS, which does not sync up with EDK2 open source often. The mismatched version of OpenSBI and sbi_platform is possible to happen.
With **opensbi_revision** declared in sbi_platform table, OpenSBI can throw an error message and halts system if the platform table version is not matched with openSBI revision. Or openSBI can return UNSUPPORTED status to the caller, so the caller can have further fallbacks processes. This reduces the debugging effort in case EDK2 developer is not aware of the inconsistency of these two structures. 
Another use case is that revsion information could be posted on screen during UEFI system POST or log to event logger for system management.

**sbi_firmware_context**
EDK2 RISC-V platform code maintains sbi_platform for the platform and build up the data structure which is delivered through mscratch. However, UEFI needs to handoff some UEFI-specific information to the next phase (such as PEI or DXE).  Current sbi_platform is not sufficient to pass any UEFI-specific information.
In order to increase the flexibility of sbi_platform for supporting any system firmware implementations and reduce the dependence between OpenSBI and specific firmware implementation. We propose to add a **sbi_firmware_context** in sbi_platform which is owned and comsumed by system firmware. 
We would like to create UEFI-specific **sbi_firmware_context** structure and publish it  in UEFI Platform Initialization spec. With this, any format changes of **sbi_firmware_context** structure don’t impact OpenSBI spec.

**Comment by avpatel** [comment]
Patches for this are merged now. Thanks Abner.
