### ISSUE TITLE
Publish RISC-V OpenSBI spec somewhere in OpenSBI repo

### ISSUE THREAD

**Issue by changab** [riscv/opensbi#110]
In order to standardize the incorporation of OpenSBI on RISC-V UEFI port in UEFI Platform Initialization spec, we need to public RISC-C OpenSBI spec somewhere in OpenSBI repo.  So we can put the external references to RISC-V OpenSBI repo as the reference of sbi_scratch and sbi_platform structure in PI spec.

**Comment by alistair23** [comment]
What do you mean by the OpenSBI spec?

Shouldn't the only interface with OpenSBI be using SBI calls?

**Comment by changab** [comment]
Yes. UEFI edk2 open source uses SBI calls. I mean we will mention OpenSBI in UEFI spec and put the external references in UEFI spec which point to OpenSBI spec, sbi_scratch, platform implementation guidance of sbi_platform and etc. The OpenSBI spec refers to "RISC-V OpenSBI v0.3.pdf". I forget how and where I got it though.

**Comment by atishp04** [comment]
@changab It is available at https://github.com/riscv/opensbi/releases 
Every release tar ball will contain the entire binary & RISC-V OpenSBI vX.Y.pdf

**Comment by changab** [comment]
Thanks, Atish!

**Comment by atishp04** [comment]
closing this issue.
