### ISSUE TITLE
MSIP is supposed to be read-only in MIP?

### ISSUE THREAD

**Issue by taylor-bsg** [riscv/opensbi#128]
https://github.com/riscv/opensbi/blob/a6395acd6cb2c35871481d3e4f0beaf449f8c0fd/lib/sbi_hart.c#L351

riscv-privileged-20190405: The mip register is an MXLEN-bit read/write register containing information on pending interrupts, while mie is the corresponding MXLEN-bit read/write register containing interrupt enable bits. Only the bits corresponding to lower-privilege software interrupts (USIP, SSIP), timer interrupts (UTIP, STIP), and external interrupts (UEIP, SEIP) in mip are writable through this CSR address; the remaining bits are read-only. 

Is this targeting older, non-compliant HW, or am I misunderstanding something?

**Comment by alistair23** [comment]
OpenSBI runs in M-mode, so it is able to access the M mode bits. See the end of that paragraph: 

>  A hart can write its own MSIP bit using the same memorymapped control register.

**Comment by taylor-bsg** [comment]
Yes, that means that you need to write to the memory location, not use the
csr write instruction.

**Comment by alistair23** [comment]
Ah yeah, it looks like you are correct. You should send a PR to the repo.

**Comment by taylor-bsg** [comment]
I guess that means that this works on Spike, SiFive silicon, or Rocket?
What are you testing on? Maybe we should file an issue on those repos.

**Comment by alistair23** [comment]
We test mostly on QEMU, HiFive UnLeashed and the Kendryte board.

**Comment by taylor-bsg** [comment]
Thanks.   We will eventually submit a pull request, but others are free to
submit it before us.

**Comment by avpatel** [comment]
We have taken care of this issue hence closing it.
