### ISSUE TITLE
Use spaces replace Tab in source code?

### ISSUE THREAD

**Issue by changab** [riscv/opensbi#129]
Shall we use space in the source code instead of using Tab? The code look in the same indent in the different editors.

**Comment by atishp04** [comment]
I think Linux coding guidelines suggests the indention should be set to 8 characters.
As long as the editor has 8 character tab settings, it shouldn't matter.

**Comment by avpatel** [comment]
@changab We are following Linux coding style so that people familiar with Linux, U-Boot, and other projects using this style can easily contribute. I think it should easy for anyone to configure their editor for Linux coding style.

**Comment by changab** [comment]
@avpatel I understand the consideration of Linux coding standard. However, OpenSBI is not just only for Linux programmer now, it will be also part of ekd2 and edk2 has it's own coding standard as well. Not insist it, I just think maybe a compromise could make different development worlds feel easy when coding. They don't have to change settings in the editor. Especially to work on two coding standards in one editor.
Thanks

**Comment by marcopeereboom** [comment]
the 90s called and they want their editor wars back
