### ISSUE TITLE
Use cpu_to_fdt32 instead of fdt32_to_cpu?

### ISSUE THREAD

**Issue by Georgeto** [riscv/opensbi#131]
https://github.com/riscv/opensbi/blob/3048f979cab3d0f42461bd4d96a4bdecf1791f62/lib/utils/irqchip/plic.c#L71

Shouldn't this be `cpu_to_fdt32(0xffffffff)`? (although it does not make a difference in this particular instance)

**Comment by avpatel** [comment]
Yes, it should be cpu_to_fdt32() for being semantically correct.

It's a typo which slipped through cracks previously.

Please send patch to OpenSBI mailing list for correcting this.

Thanks,
Anup

**Comment by avpatel** [comment]
I forgot to mention.

You can join OpenSBI mailing list using following link:
http://lists.infradead.org/mailman/listinfo/opensbi

**Comment by Georgeto** [comment]
I posted a patch on the OpenSBI mailing list, and also subscribed to it.

**Comment by avpatel** [comment]
Yes, got your patch on list.

I will merge it tomorrow.

Thanks,
Anup

**Comment by avpatel** [comment]
Applied your patch.

Thanks,
Anup
