### ISSUE TITLE
The values of CAUSE_HYPERVISOR_ECALL and CAUSE_SUPERVISOR_ECALL macro

### ISSUE THREAD

**Issue by knknkn1162** [riscv/opensbi#139]
Hi.

I noticed that the values of CAUSE_HYPERVISOR_ECALL and CAUSE_SUPERVISOR_ECALL are actually reversed. Is it right?

https://github.com/riscv/opensbi/blob/be92da280d87c38a2e0adc5d3f43bab7b5468f09/include/sbi/riscv_encoding.h#L472-L473

Whereas, the [Privileged ISA Specification; 20190608version](https://riscv.org/specifications/privileged-isa/) says below:

![スクリーンショット 2019-10-21 14 08 13](https://user-images.githubusercontent.com/10457551/67178087-6f8ff100-f40c-11e9-97e7-d54bf27e9674.jpg)

**Comment by avpatel** [comment]
Maybe the #define name are little miss-leading but when H-extension is available:
0x9 => Environment call from HS-mode
0xa => Environment call from VS-mode

The rationale is that when H-extension is available, the traditional S-mode is actually HS-mode
with hypervisor capabilities.

All ECALLs from VS-mode should be handled in HS-mode only hence we are delegating CAUSE_SUPERVISOR_ECALL to HS-mode when H-extension is available.
(Refer, delegate_traps() in opensbi/lib/sbi/sbi_hart.c)

I hope above info helps.

Regards,
Anup

**Comment by knknkn1162** [comment]
I see.. Unfortunately, I'm currently not very familiar with H(Hypervisor)-mode, but I understood what you comment. Thank you!

**Comment by avpatel** [comment]
Closing this issue now.
