### ISSUE TITLE
Dynamic IPI registration

### ISSUE THREAD

**Issue by dayeol** [riscv/opensbi#147]
Hi,

I have another question regarding PMP.
Currently, I see that PMP is initialized at `sbi_hart_init()`, which is one-time called per-hart at boot.

Keystone Enclave uses PMP for dynamic memory isolation, and all of the PMP entries in all cores must be synchronized when an enclave is created/destroyed.

In bbl version of keystone, we have done it by adding a custom IPl, where one core initiates the IPI to update PMP entries and then waits until all the other cores finishes updating PMP.

I see there is no way for now to cleanly add a custom IPI without changing the core functions like `sbi_ipi_process()`.
Do you have any suggestions on what would be the best way to add this?

**Comment by avpatel** [comment]
For IPI, we will provide register/unregister mechanism just like experimental SBI extensions.

Regards,
Anup

**Comment by dayeol** [comment]
Wonderful. Thanks!

**Comment by avpatel** [comment]
I have sent-out a patch series for this to OpenSBI mailing list.

To join, OpenSBI mailing list visit:
http://lists.infradead.org/mailman/listinfo/opensbi

Regards,
Anup

**Comment by avpatel** [comment]
Patches are reviewed and merged. Please try at your end.

Regards,
Anup
