### ISSUE TITLE
Can opensbi support smp directly? without uboot

### ISSUE THREAD

**Issue by kiutao** [riscv/opensbi#150]
I try to boot linux  using opensbi directly. 
one core: success
8cores:
[ 0.000992] smp: Bringing up secondary CPUs …
[ 1.057750] CPU1: failed to come online
.....
only one core can work..

**Comment by kiutao** [comment]
solved.

**Comment by MarcKarasek** [comment]
How did you solve this?  I am seeing the same thing under qemu.  I recently upgraded to qemu 6 from 5.

**Comment by avpatel** [comment]
For OpenSBI v0.7 (or higher), use Linux-5.7 (or higher).

The OpenSBI v0.7 implement SBI HSM extension which brings ordered booting of HARTs on SMP host.

If you want to use older Linux with OpenSBI v0.7 (or higher) then you can back-port Linux SBI v0.2 support patches.

I hope above info helps.

Thanks,
Anup
