### ISSUE TITLE
About the problem of booting OpenSBI  in versions before LinuxKernel 5.7

### ISSUE THREAD

**Issue by nylon7** [riscv/opensbi#168]
Currently OpenSBI-v0.7 version included HSM, but versions before Kernel 5.7 do not support HSM.

As a result, there is no HSM in the Kernel for the master core to wake up the slave core.

I was wondering if we could apply @atishp04 's patch to solve the issue.
https://patchwork.kernel.org/cover/11395187/

**Comment by avpatel** [comment]
Yes, you can backport Linux SBI 0.2 patches for older kernel (earlier than linux-5.7).

Regards,
Anup

**Comment by avpatel** [comment]
I hope my previous comment helped.

If possible please close this issue.

Regards,
Anup

**Comment by nylon7** [comment]
@avpatel 

Thank you for your help. :D

I've already finished.
