### ISSUE TITLE
Simulation on Spike

### ISSUE THREAD

**Issue by johnnavaj** [riscv/opensbi#175]
Folks,

I have been trying to simulate opensbi on spike along with a simple rom code ( Zbsl -> fsbl(opensbi)), once i execute my rom code i do a jump to text section allocated at 0x80500000 but it hangs there. 

Tried to direct boot opensbi without rom still  i am having the same issue over spike and gdb. 

But if i execute on spike(same text section  allocation  address)  it works with the splash screen , pmp info etc. 

any pointers here ?

**Comment by johnnavaj** [comment]
Closing this since its solved.

**Comment by OrkunAliOzkan** [comment]
> Closing this since its solved.

Hi, can you please run through your steps?
