### ISSUE TITLE
what is the main function of "sbi_hart_set_trap_info(scratch, trap);" and "sbi_hart_set_trap_info(scratch, NULL);embrace code?

### ISSUE THREAD

**Issue by 13824125580** [riscv/opensbi#176]
Hi folks:
 
    in the oensbi code, there are usually  a code style like this:
    .........................................................
    **sbi_hart_set_trap_info(scratch, trap);**
    //build in assemble language.
    ...............................
    ...............................
    **sbi_hart_set_trap_info(scratch, NULL);**

for example:
 **29                 sbi_hart_set_trap_info(scratch, trap);                        \**
 30                 asm volatile(                                                 \
 31                         "csrrs %0, " STR(CSR_MSTATUS) ", %3\n"                \                                                                                                            
 32                         ".option push\n"                                      \
 33                         ".option norvc\n"                                     \
 34                         #insn " %1, %2\n"                                     \
 35                         ".option pop\n"                                       \
 36                         "csrw " STR(CSR_MSTATUS) ", %0"                       \
 37                 ¦   : "+&r"(__mstatus), "=&r"(val)                            \
 38                 ¦   : "m"(*addr), "r"(MSTATUS_MPRV));                         \
 **39                 sbi_hart_set_trap_info(scratch, NULL);                        \**
 40                 return val;                                                   \

    so,what is the use of symmetry use  of this  api ?

thank you!

**Comment by avpatel** [comment]
This was for capturing trap details for M-mode to M-mode trap while doing unprivileged access.

This function does not exist anymore because we have new way to capture trap details for M-mode to M-mode trap.

Regards,
Anup

**Comment by 13824125580** [comment]
from which version change to the new way？@avpatel

**Comment by avpatel** [comment]
This change happened between v0.6 and v0.7 release

Regards,
Anup

**Comment by avpatel** [comment]
I assume this is resolved hence closing the issue.
