### ISSUE TITLE
Potential bug in fw_base.S lottery code?

### ISSUE THREAD

**Issue by MarcKarasek** [riscv/opensbi#179]
I was looking at the fw_base.S code for our SOC and saw this:

/* Jump to relocation wait loop if we don't get relocation lottery */
	la	a6, _relocate_lottery
	li	a7, 1
	amoadd.w a6, a7, (a6)
	bnez	a6, _wait_relocate_copy_done

From what I understand the amoadd.w rd,rs2,(rs1)  each register should be different.  
In the above rd will end up with the value read from (rs1).  Since both are the same and at the end the value of rd + rs2 is stored back to what is in (rs1).  It looks like you will be writing to (0) rather than back to what was in r6 (memory location of _relocate_lottery).  

So the seq would be something like this.  read (a6), put this value into a6, add a6 + a7 and store back to (a6).

Marc

**Comment by avpatel** [comment]
I assume this is resolved hence closing the issue.

**Comment by BabyMelvin** [comment]
I have the same doubt about this issue. Of course, i am a freshman for RISC-V ISA.

There is some description at **8.4 Atomic Memory Operations** from the risc-v spec:
```
     These AMO instructions atomically load a data value from the address in rs1, place the value into register rd,
apply a binary operator to the loaded value and the original value in rs2, then store the result back
to the address in rs1.
```
These descriptions just like this steps:

1. rd <- mem[rs1]
2. mem[rs1] <- mem[rs1]  op rs2

rd seems to be updated at the first step? And how to print the (a6) value with gdb？

Thanks a lot.
