### ISSUE TITLE
 Which is the easiest way to boot linux with opensbi

### ISSUE THREAD

**Issue by dskwe** [riscv/opensbi#180]
I found several ways to boot linux with opensbi in a new platform:
a) specific fsbl->opensbi->linux
b) specific fsbl->opensbi->u-boot->linux
c) u-boot-spl->opensbi->u-boot->linux

I wonder which way is the easiest. I prefer a) , use opensbi firmware FW_PAYLOAD and set  linux kernel image as the payload. In this way, I don’t need to care about u-boot related code. The work will be focused on opensbi and linux. 
But it seems c) is the mainstream boot flow?

**Comment by dskwe** [comment]
Are there some examples for a)? 
Reference links would be helpful, thanks.

**Comment by avpatel** [comment]
For a), usually FPGA platforms use this approach. You can look at docs/platform/fpga-ariane.md OR docs/platform/shakti_cclass.md. The biggest issue with a) is that we have to recreate fw_payload.bin whenever kernel image changes.

For b) and c), mostly real world SoC tend to use these flows. We have U-Boot (or some other open source bootloader) which provides advance booting methods (such as network booting). We can load kernel image from SD card OR Flash OR TFTP without changing firmware or bootloader.

The c) approach is most flexible because we can upgrade any image in the boot flow without changing other images.

Regards,
Anup

**Comment by dskwe** [comment]
Yes, I'm doing my work on a FPGA, and want to use the a) approach.
What about platform/sifive_fu540? I have read linux and opensbi code for sifive_fu640, and would like to do some work based on the mainline of these two git repositories. 
On your suggestion, the FPGA platform such as fpga-ariane or shakti would be a better example for me?

**Comment by dskwe** [comment]
> For a), usually FPGA platforms use this approach. You can look at docs/platform/fpga-ariane.md OR docs/platform/shakti_cclass.md. The biggest issue with a) is that we have to recreate fw_payload.bin whenever kernel image changes.
> 
> For b) and c), mostly real world SoC tend to use these flows. We have U-Boot (or some other open source bootloader) which provides advance booting methods (such as network booting). We can load kernel image from SD card OR Flash OR TFTP without changing firmware or bootloader.
> 
> The c) approach is most flexible because we can upgrade any image in the boot flow without changing other images.
> 
> Regards,
> Anup

Yes, I'm doing my work on a FPGA, and want to use the a) approach.
What about platform/sifive_fu540? I have read linux and opensbi code for sifive_fu640, and would like to do some work based on the mainline of these two git repositories.
On your suggestion, the FPGA platform such as fpga-ariane or shakti would be a better example for me?

**Comment by avpatel** [comment]
I don't think there is FU640 from SiFive. Did you mean FU540?

The shakti_cclass support uses OpenSBI generic platform so I recommend you can take similar route but if you want to do things differently from OpenSBI generic platform then you can take fpga-ariane as reference.
 
Regards,
Anup

**Comment by dskwe** [comment]
Yes, actually I mean  FU540. 

Thank you.

> I don't think there is FU640 from SiFive. Did you mean FU540?
> 
> The shakti_cclass support uses OpenSBI generic platform so I recommend you can take similar route but if you want to do things differently from OpenSBI generic platform then you can take fpga-ariane as reference.
> 
> Regards,
> Anup

**Comment by avpatel** [comment]
I assume your issue is resolved. Can we close this issue?

Regards,
Anup

**Comment by dskwe** [comment]
Sure.
