### ISSUE TITLE
What is the rule for the custom error codes?

### ISSUE THREAD

**Issue by dayeol** [riscv/opensbi#190]
Hello, I have a quick question.
What's the rule to define additional error codes for custom ecall?

Thanks in advance!

**Comment by avpatel** [comment]
The standard error codes defined by SBI spec are generally close to -1 so the OpenSBI itself uses error codes < -1000 for OpenSBI specific error code. You can choose a much higher order negative number for your custom error code (such as < -10000)

Regards,
Anup

**Comment by dayeol** [comment]
Thanks! Closing the issue
