### ISSUE TITLE
sbi_console_getchar() should return int and not char

### ISSUE THREAD

**Issue by xerpi** [riscv/opensbi#72]
According to the [SBI specification](https://github.com/riscv/riscv-sbi-doc/blob/master/riscv-sbi.md), `sbi_console_getchar()` returns an `int`instead of a `char` (as currently defined in `struct sbi_platform`).

[Linux also considers it](https://github.com/torvalds/linux/blob/master/arch/riscv/include/asm/sbi.h#L51) as returning an `int`, and [checks it to be non-negative](https://github.com/torvalds/linux/blob/master/drivers/tty/hvc/hvc_riscv_sbi.c#L33).

EDIT: I have checked the output of returning `-1` and the disassembly shows `li a0, 255`, which is wrong (should be 2^32 - 1), and Linux interprets it as a "weird" character.

**Comment by atishp04** [comment]
Thanks for reporting this. Fixed in #76

**Comment by atishp04** [comment]
Fixed and merged. Closing the issue.
